import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import { headers } from "next/headers";
import Image from "next/image";
import ParallaxBg from "@/components/ui/animation/parallax-bg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getCurrentPathname(): Promise<string | undefined> {
  const h = await headers();
  const candidates = [
    h.get("x-invoke-path"),
    h.get("x-pathname"),
    h.get("next-url"),
    h.get("x-url"),
  ].filter(Boolean) as string[];
  const raw = candidates[0];
  if (!raw) return undefined;
  try {
    if (raw.startsWith("http://") || raw.startsWith("https://")) {
      const u = new URL(raw);
      return u.pathname || "/";
    }
    return raw.split("?")[0] || "/";
  } catch {
    return raw.split("?")[0] || "/";
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const activePath = await getCurrentPathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header activePath={activePath} logo={<Image src="/logo.svg" alt="CryptoDashboard" width={36} height={36} />} />
        {children}
        <ParallaxBg />
      </body>
    </html>
  );
}
